#!/bin/bash

function createCompany() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/company.example.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/company.example.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:7054 --caname ca-company --tls.certfiles "${PWD}/organizations/fabric-ca/company/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-company.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-company.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-company.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-company.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/company.example.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy company's CA cert to company's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/company.example.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/company/ca-cert.pem" "${PWD}/organizations/peerOrganizations/company.example.com/msp/tlscacerts/ca.crt"

  # Copy company's CA cert to company's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/company.example.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/company/ca-cert.pem" "${PWD}/organizations/peerOrganizations/company.example.com/tlsca/tlsca.company.example.com-cert.pem"

  # Copy company's CA cert to company's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/company.example.com/ca"
  cp "${PWD}/organizations/fabric-ca/company/ca-cert.pem" "${PWD}/organizations/peerOrganizations/company.example.com/ca/ca.company.example.com-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-company --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/company/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-company --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/company/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-company --id.name companyadmin --id.secret companyadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/company/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-company -M "${PWD}/organizations/peerOrganizations/company.example.com/peers/peer0.company.example.com/msp" --csr.hosts peer0.company.example.com --tls.certfiles "${PWD}/organizations/fabric-ca/company/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/company.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/company.example.com/peers/peer0.company.example.com/msp/config.yaml"

  infoln "Generating the peer0-tls certificates"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-company -M "${PWD}/organizations/peerOrganizations/company.example.com/peers/peer0.company.example.com/tls" --enrollment.profile tls --csr.hosts peer0.company.example.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/company/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/company.example.com/peers/peer0.company.example.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/company.example.com/peers/peer0.company.example.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/company.example.com/peers/peer0.company.example.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/company.example.com/peers/peer0.company.example.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/company.example.com/peers/peer0.company.example.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/company.example.com/peers/peer0.company.example.com/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:7054 --caname ca-company -M "${PWD}/organizations/peerOrganizations/company.example.com/users/User1@company.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/company/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/company.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/company.example.com/users/User1@company.example.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://companyadmin:companyadminpw@localhost:7054 --caname ca-company -M "${PWD}/organizations/peerOrganizations/company.example.com/users/Admin@company.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/company/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/company.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/company.example.com/users/Admin@company.example.com/msp/config.yaml"
}

function createPerson() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/person.example.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/person.example.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:8054 --caname ca-person --tls.certfiles "${PWD}/organizations/fabric-ca/person/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-person.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-person.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-person.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-person.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/person.example.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy person's CA cert to person's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/person.example.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/person/ca-cert.pem" "${PWD}/organizations/peerOrganizations/person.example.com/msp/tlscacerts/ca.crt"

  # Copy person's CA cert to person's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/person.example.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/person/ca-cert.pem" "${PWD}/organizations/peerOrganizations/person.example.com/tlsca/tlsca.person.example.com-cert.pem"

  # Copy person's CA cert to person's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/person.example.com/ca"
  cp "${PWD}/organizations/fabric-ca/person/ca-cert.pem" "${PWD}/organizations/peerOrganizations/person.example.com/ca/ca.person.example.com-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-person --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/person/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-person --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/person/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-person --id.name personadmin --id.secret personadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/person/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-person -M "${PWD}/organizations/peerOrganizations/person.example.com/peers/peer0.person.example.com/msp" --csr.hosts peer0.person.example.com --tls.certfiles "${PWD}/organizations/fabric-ca/person/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/person.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/person.example.com/peers/peer0.person.example.com/msp/config.yaml"

  infoln "Generating the peer0-tls certificates"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-person -M "${PWD}/organizations/peerOrganizations/person.example.com/peers/peer0.person.example.com/tls" --enrollment.profile tls --csr.hosts peer0.person.example.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/person/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/person.example.com/peers/peer0.person.example.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/person.example.com/peers/peer0.person.example.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/person.example.com/peers/peer0.person.example.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/person.example.com/peers/peer0.person.example.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/person.example.com/peers/peer0.person.example.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/person.example.com/peers/peer0.person.example.com/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:8054 --caname ca-person -M "${PWD}/organizations/peerOrganizations/person.example.com/users/User1@person.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/person/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/person.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/person.example.com/users/User1@person.example.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://personadmin:personadminpw@localhost:8054 --caname ca-person -M "${PWD}/organizations/peerOrganizations/person.example.com/users/Admin@person.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/person/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/person.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/person.example.com/users/Admin@person.example.com/msp/config.yaml"
}

function createGovernment() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/government.example.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/government.example.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:9054 --caname ca-government --tls.certfiles "${PWD}/organizations/fabric-ca/government/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-government.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-government.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-government.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-government.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/government.example.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy government's CA cert to government's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/government.example.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/government/ca-cert.pem" "${PWD}/organizations/peerOrganizations/government.example.com/msp/tlscacerts/ca.crt"

  # Copy government's CA cert to government's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/government.example.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/government/ca-cert.pem" "${PWD}/organizations/peerOrganizations/government.example.com/tlsca/tlsca.government.example.com-cert.pem"

  # Copy government's CA cert to government's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/government.example.com/ca"
  cp "${PWD}/organizations/fabric-ca/government/ca-cert.pem" "${PWD}/organizations/peerOrganizations/government.example.com/ca/ca.government.example.com-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-government --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/government/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-government --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/government/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-government --id.name governmentadmin --id.secret governmentadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/government/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:9054 --caname ca-government -M "${PWD}/organizations/peerOrganizations/government.example.com/peers/peer0.government.example.com/msp" --csr.hosts peer0.government.example.com --tls.certfiles "${PWD}/organizations/fabric-ca/government/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/government.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/government.example.com/peers/peer0.government.example.com/msp/config.yaml"

  infoln "Generating the peer0-tls certificates"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:9054 --caname ca-government -M "${PWD}/organizations/peerOrganizations/government.example.com/peers/peer0.government.example.com/tls" --enrollment.profile tls --csr.hosts peer0.government.example.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/government/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/government.example.com/peers/peer0.government.example.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/government.example.com/peers/peer0.government.example.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/government.example.com/peers/peer0.government.example.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/government.example.com/peers/peer0.government.example.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/government.example.com/peers/peer0.government.example.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/government.example.com/peers/peer0.government.example.com/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:9054 --caname ca-government -M "${PWD}/organizations/peerOrganizations/government.example.com/users/User1@government.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/government/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/government.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/government.example.com/users/User1@government.example.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://governmentadmin:governmentadminpw@localhost:9054 --caname ca-government -M "${PWD}/organizations/peerOrganizations/government.example.com/users/Admin@government.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/government/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/government.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/government.example.com/users/Admin@government.example.com/msp/config.yaml"
}

function createTargetC() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/targetc.example.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/targetc.example.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:10054 --caname ca-targetc --tls.certfiles "${PWD}/organizations/fabric-ca/targetc/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-10054-ca-targetc.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-10054-ca-targetc.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-10054-ca-targetc.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-10054-ca-targetc.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/targetc.example.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy targetc's CA cert to targetc's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/targetc.example.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/targetc/ca-cert.pem" "${PWD}/organizations/peerOrganizations/targetc.example.com/msp/tlscacerts/ca.crt"

  # Copy targetc's CA cert to targetc's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/targetc.example.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/targetc/ca-cert.pem" "${PWD}/organizations/peerOrganizations/targetc.example.com/tlsca/tlsca.targetc.example.com-cert.pem"

  # Copy targetc's CA cert to targetc's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/targetc.example.com/ca"
  cp "${PWD}/organizations/fabric-ca/targetc/ca-cert.pem" "${PWD}/organizations/peerOrganizations/targetc.example.com/ca/ca.targetc.example.com-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-targetc --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/targetc/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-targetc --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/targetc/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-targetc --id.name targetcadmin --id.secret targetcadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/targetc/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:10054 --caname ca-targetc -M "${PWD}/organizations/peerOrganizations/targetc.example.com/peers/peer0.targetc.example.com/msp" --csr.hosts peer0.targetc.example.com --tls.certfiles "${PWD}/organizations/fabric-ca/targetc/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/targetc.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/targetc.example.com/peers/peer0.targetc.example.com/msp/config.yaml"

  infoln "Generating the peer0-tls certificates"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:10054 --caname ca-targetc -M "${PWD}/organizations/peerOrganizations/targetc.example.com/peers/peer0.targetc.example.com/tls" --enrollment.profile tls --csr.hosts peer0.targetc.example.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/targetc/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/targetc.example.com/peers/peer0.targetc.example.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/targetc.example.com/peers/peer0.targetc.example.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/targetc.example.com/peers/peer0.targetc.example.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/targetc.example.com/peers/peer0.targetc.example.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/targetc.example.com/peers/peer0.targetc.example.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/targetc.example.com/peers/peer0.targetc.example.com/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:10054 --caname ca-targetc -M "${PWD}/organizations/peerOrganizations/targetc.example.com/users/User1@targetc.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/targetc/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/targetc.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/targetc.example.com/users/User1@targetc.example.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://targetcadmin:targetcadminpw@localhost:10054 --caname ca-targetc -M "${PWD}/organizations/peerOrganizations/targetc.example.com/users/Admin@targetc.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/targetc/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/targetc.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/targetc.example.com/users/Admin@targetc.example.com/msp/config.yaml"
}

function createTargetCOrderer() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/ordererOrganizations/example.com

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/ordererOrganizations/example.com

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:11054 --caname ca-orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-orderer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-orderer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-orderer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-orderer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/ordererOrganizations/example.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy orderer org's CA cert to orderer org's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/example.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/example.com/msp/tlscacerts/tlsca.example.com-cert.pem"

  # Copy orderer org's CA cert to orderer org's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/ordererOrganizations/example.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/example.com/tlsca/tlsca.example.com-cert.pem"

  infoln "Registering orderer"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name orderer --id.secret ordererpw --id.type orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the orderer admin"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name ordererAdmin --id.secret ordererAdminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the orderer msp"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:11054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp" --csr.hosts orderer.example.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/example.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp/config.yaml"

  infoln "Generating the orderer-tls certificates"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:11054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls" --enrollment.profile tls --csr.hosts orderer.example.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
  cp "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/ca.crt"
  cp "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/signcerts/"* "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt"
  cp "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/keystore/"* "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.key"

  # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts"
  cp "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem"

  infoln "Generating the admin msp"
  set -x
  fabric-ca-client enroll -u https://ordererAdmin:ordererAdminpw@localhost:11054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/example.com/users/Admin@example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/example.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/example.com/users/Admin@example.com/msp/config.yaml"
}
